import Head from "next/head";
import Button from "components/Button";
import H2 from "modules/H2";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <H2 />
      <Button />
    </div>
  );
}
